### ISSUE TITLE
Mismatched operands

### ISSUE THREAD

**Issue by v6** [rjb25/5e-dm-assistant#16]
Looks like we've got a lot of cases of collection defaultdict getting compared to integer values. 

Not sure what's going on here, but here's just one example: 

```
Command?add --times 5 --target adult-black-dragon tyrone-the-dragon
17d12
oneechan makes awkward-sounding noises at you, enter the 'exit' command to exit.
Traceback (most recent call last):
  File "basic.py", line 701, in run_assistant
    running = parse_command(command_input_string)
  File "basic.py", line 681, in parse_command
    command_result += str(funcDict[command](argDictCopy))
  File "basic.py", line 509, in addCreature
    applyInit({"target" : nick})
  File "basic.py", line 292, in applyInit
    combatant["initiative"] = statMod(combatant["dexterity"]) + roll("1d20")
  File "basic.py", line 240, in statMod
    return math.floor((stat-10)/2)
TypeError: unsupported operand type(s) for -: 'collections.defaultdict' and 'int'
initiative name type hp/max_hp
22 giant-rat giant-rat 3/3
12 sahuagin#1 sahuagin 11/11
9 goblin goblin 9/9
3 druid druid 21/23
Command?
```

**Comment by v6** [comment]
'snot just for Tyrone either: 

```
Command?add --times 5 --target giant-rat rattigan-the-rat
2d6
oneechan makes awkward-sounding noises at you, enter the 'exit' command to exit.
Traceback (most recent call last):
  File "basic.py", line 701, in run_assistant
    running = parse_command(command_input_string)
  File "basic.py", line 681, in parse_command
    command_result += str(funcDict[command](argDictCopy))
  File "basic.py", line 509, in addCreature
    applyInit({"target" : nick})
  File "basic.py", line 292, in applyInit
    combatant["initiative"] = statMod(combatant["dexterity"]) + roll("1d20")
  File "basic.py", line 240, in statMod
    return math.floor((stat-10)/2)
TypeError: unsupported operand type(s) for -: 'collections.defaultdict' and 'int'
initiative name type hp/max_hp
22 giant-rat giant-rat 3/3
12 sahuagin#1 sahuagin 11/11
9 goblin goblin 9/9
3 druid druid 21/23
Command?
```

**Comment by rjb25** [comment]
--identity is for Nick names

**Comment by v6** [comment]
'snot just for Tyrone either: 

```
Command?add --times 5 --target giant-rat rattigan-the-rat
2d6
oneechan makes awkward-sounding noises at you, enter the 'exit' command to exit.
Traceback (most recent call last):
  File "basic.py", line 701, in run_assistant
    running = parse_command(command_input_string)
  File "basic.py", line 681, in parse_command
    command_result += str(funcDict[command](argDictCopy))
  File "basic.py", line 509, in addCreature
    applyInit({"target" : nick})
  File "basic.py", line 292, in applyInit
    combatant["initiative"] = statMod(combatant["dexterity"]) + roll("1d20")
  File "basic.py", line 240, in statMod
    return math.floor((stat-10)/2)
TypeError: unsupported operand type(s) for -: 'collections.defaultdict' and 'int'
initiative name type hp/max_hp
22 giant-rat giant-rat 3/3
12 sahuagin#1 sahuagin 11/11
9 goblin goblin 9/9
3 druid druid 21/23
Command?
```

**Comment by rjb25** [comment]
Full command should be add --times 5 --target giant-rat --identity rattigan-the-rat

**Comment by rjb25** [comment]
Looking into a better error message for this.

**Comment by rjb25** [comment]
Resolved and future issues should be easier to find.
